name:                devicetree
version:             0.1.0.0
github:              "wangbj/devicetree"
license:             BSD3
author:              "Baojun Wang"
maintainer:          "wangbj@gmail.com"
copyright:           "2018 Baojun Wang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Linux device tree parser
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/wangbj/devicetree#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10
- cereal >= 0.5
- derive-storable >= 0.1
- containers >= 0.5
- mtl >= 2.2
- QuickCheck >= 2.10
- hspec >= 2.4
- zip >= 1.0
- text >= 1.2
- criterion >= 1.3
- deepseq >= 1.4
- attoparsec >= 0.13

library:
  source-dirs: src

executables:
  devicetree-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - devicetree

tests:
  devicetree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - devicetree
    - QuickCheck >= 2.10
    - hspec >= 2.4
    - zip >= 1.0
    - text >= 1.2

benchmarks:
  devicetree-bench:
    main:                Perf.hs
    source-dirs:         benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - devicetree
    - criterion >= 1.3
    - zip >= 1.0
    - text >= 1.2
